### ISSUE TITLE
login issue with vco version 3.3.1

### ISSUE THREAD

**Issue by misc2410** [iddocohen/vcoclient#2]
dear iddo,

since my vco is updated to 3.3.1 I'm not able to login anymore. do you can imagine the reason for that?

Regards

**Comment by iddocohen** [comment]
Looks good to me (logged in to 3.3.1) - I tried it via global variables and passing via argument.

Here the example with global variables (not showing the real exports):

![image](https://user-images.githubusercontent.com/20091479/65370757-a7b0e200-dc5c-11e9-9633-617a4a25667d.png)

Could you share exact details what you experience?

**Comment by iddocohen** [comment]
I have also checked with others and they could not confirm any login problems (as operator or no-operator). Going to close the ticket for now, feel free to reopen with detail description of the fault.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by misc2410** [comment]
Hi iddo,

thank you very much for your answer and investigation. I'm still not able to dial in as you can see in the screenshot below. Am I do anything wrong?

![vcoclient](https://user-images.githubusercontent.com/55543048/65683627-0069eb80-e05e-11e9-8213-c6c08b022007.png)

Thank you very much.
Regards
Michael

**Comment by iddocohen** [comment]
It seems that test@schwarzmichael.com with given password are not defined and/or have the rights to access the APIs for vco8-fra1. Please check with your SE or support why that is the case.

**Comment by iddocohen** [comment]
I see another potential problem, please use "--no-operator" if your username is not operator

**Comment by misc2410** [comment]
Thank you very much, with --no-operator I'm now able to login. This is very strange, before the update to 3.3.1 it was possible without. Nevertheless, now I have the issue that it seems that I have not enough priviledges to run for example "edges_get". 
So at the end - thank you very much again. I enjoy your tool :)

**Comment by iddocohen** [comment]
BTW, as you are saying this, my suspicion is that user used to be operator (hence no --no-operator was needed) and edges_get worked for you to get all edges. Now as you are not operator anymore, you will need to supply a --enterpriseid, to be able to get the given edges. 

Check if from 3.3.0 to 3.3.1 you user privilege has changed. My suspicion is, it has.
